# ============================================================================
# PREVIEW CLEANUP WORKFLOW
# ============================================================================
#
# Automatically cleans up preview sites when pull requests are closed.
# Deletes the site, DNS record, and optionally the provisioned server.
#
# HOW TO USE:
# 1. Ensure ROOT_DOMAIN matches your preview-deploy.yml configuration
# 2. Uncomment the DNS provider block matching your preview-deploy.yml choice
# 3. If using per-PR provisioned servers, uncomment the server deletion block
#
# ============================================================================
# REQUIRED GITHUB SECRETS
# ============================================================================
#
# Same secrets as preview-deploy.yml - see that file for full documentation.
#
# ============================================================================

name: Preview Cleanup

on:
  pull_request:
    types: [closed]

env:
  # ==========================================================================
  # CONFIGURATION - Must match preview-deploy.yml settings
  # ==========================================================================
  ROOT_DOMAIN: "previews.example.com"

jobs:
  cleanup:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # ========================================================================
      # SETUP
      # ========================================================================

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, curl, zip
          coverage: none

      - name: Install DeployerPHP
        run: composer global require deployer-php/deployer-php

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYER_SSH_KEY }}" > ~/.ssh/deployer
          chmod 600 ~/.ssh/deployer

      - name: Restore inventory
        run: |
          mkdir -p ~/.deployer
          echo "${{ secrets.DEPLOYER_INVENTORY }}" | base64 -d > ~/.deployer/inventory.json

      - name: Generate subdomain
        id: subdomain
        run: |
          # Must match the logic in preview-deploy.yml
          TITLE="${{ github.event.pull_request.title }}"
          SANITIZED=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | \
            sed 's/[^a-z0-9-]/-/g' | \
            sed 's/--*/-/g' | \
            sed 's/^-//' | \
            sed 's/-$//' | \
            cut -c1-30)
          SUBDOMAIN="pr-${{ github.event.pull_request.number }}-${SANITIZED}"
          FQDN="${SUBDOMAIN}.${{ env.ROOT_DOMAIN }}"

          echo "subdomain=${SUBDOMAIN}" >> $GITHUB_OUTPUT
          echo "fqdn=${FQDN}" >> $GITHUB_OUTPUT
          echo "Cleaning up preview: ${FQDN}"

      - name: Post cleanup status
        uses: actions/github-script@v7
        with:
          script: |
            const body = `## Preview Deployment

            | Status | Details |
            |--------|---------|
            | :broom: | Cleaning up preview environment... |

            **Domain:** \`${{ steps.subdomain.outputs.fqdn }}\``;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const botComment = comments.find(c =>
              c.user.login === 'github-actions[bot]' &&
              c.body.includes('## Preview Deployment')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            }

      # ========================================================================
      # SITE DELETION
      # ========================================================================

      - name: Delete site
        continue-on-error: true
        run: |
          # Check if site exists before trying to delete
          if deployer site:info --domain="${{ steps.subdomain.outputs.fqdn }}" &>/dev/null; then
            deployer site:delete \
              --domain="${{ steps.subdomain.outputs.fqdn }}" \
              --force \
              --yes
            echo "Site deleted successfully"
          else
            echo "Site does not exist, skipping deletion"
          fi

      # ========================================================================
      # DNS RECORD DELETION - Uncomment ONE provider (must match preview-deploy.yml)
      # ========================================================================

      # ------------------------------------------------------------------------
      # OPTION A: AWS Route53
      # ------------------------------------------------------------------------
      # Required secrets: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_ROUTE53_ZONE_ID
      #
      # - name: Delete DNS record (Route53)
      #   continue-on-error: true
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1
      #   run: |
      #     deployer pro:aws:dns:delete \
      #       --zone="${{ secrets.AWS_ROUTE53_ZONE_ID }}" \
      #       --type=A \
      #       --name="${{ steps.subdomain.outputs.subdomain }}" \
      #       --force \
      #       --yes || echo "DNS record may not exist, continuing..."

      # ------------------------------------------------------------------------
      # OPTION B: DigitalOcean DNS
      # ------------------------------------------------------------------------
      # Required secrets: DIGITALOCEAN_TOKEN
      #
      # - name: Delete DNS record (DigitalOcean)
      #   continue-on-error: true
      #   env:
      #     DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      #   run: |
      #     deployer pro:do:dns:delete \
      #       --zone="${{ env.ROOT_DOMAIN }}" \
      #       --type=A \
      #       --name="${{ steps.subdomain.outputs.subdomain }}" \
      #       --force \
      #       --yes || echo "DNS record may not exist, continuing..."

      # ------------------------------------------------------------------------
      # OPTION C: Cloudflare
      # ------------------------------------------------------------------------
      # Required secrets: CLOUDFLARE_API_TOKEN, CLOUDFLARE_ZONE_ID
      #
      # - name: Delete DNS record (Cloudflare)
      #   continue-on-error: true
      #   env:
      #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #   run: |
      #     deployer pro:cf:dns:delete \
      #       --zone="${{ secrets.CLOUDFLARE_ZONE_ID }}" \
      #       --type=A \
      #       --name="${{ steps.subdomain.outputs.subdomain }}" \
      #       --force \
      #       --yes || echo "DNS record may not exist, continuing..."

      # ========================================================================
      # SERVER DELETION (Optional - only if using per-PR provisioned servers)
      # ========================================================================
      #
      # Uncomment ONE of these blocks if you're provisioning servers per-PR
      # and want them deleted when the PR closes.
      #
      # WARNING: This permanently destroys the server and all data on it.
      #

      # ------------------------------------------------------------------------
      # OPTION A: Delete AWS EC2 instance
      # ------------------------------------------------------------------------
      # Required secrets: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
      #
      # - name: Delete AWS server
      #   continue-on-error: true
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1
      #   run: |
      #     SERVER_NAME="preview-${{ github.event.pull_request.number }}"
      #     if deployer server:info --server="${SERVER_NAME}" &>/dev/null; then
      #       deployer server:delete \
      #         --server="${SERVER_NAME}" \
      #         --force \
      #         --yes
      #       echo "Server ${SERVER_NAME} deleted successfully"
      #     else
      #       echo "Server ${SERVER_NAME} does not exist, skipping"
      #     fi

      # ------------------------------------------------------------------------
      # OPTION B: Delete DigitalOcean droplet
      # ------------------------------------------------------------------------
      # Required secrets: DIGITALOCEAN_TOKEN
      #
      # - name: Delete DigitalOcean server
      #   continue-on-error: true
      #   env:
      #     DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      #   run: |
      #     SERVER_NAME="preview-${{ github.event.pull_request.number }}"
      #     if deployer server:info --server="${SERVER_NAME}" &>/dev/null; then
      #       deployer server:delete \
      #         --server="${SERVER_NAME}" \
      #         --force \
      #         --yes
      #       echo "Server ${SERVER_NAME} deleted successfully"
      #     else
      #       echo "Server ${SERVER_NAME} does not exist, skipping"
      #     fi

      # ========================================================================
      # STATUS UPDATE
      # ========================================================================

      - name: Post final status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const wasSuccess = '${{ job.status }}' === 'success';
            const statusIcon = wasSuccess ? ':white_check_mark:' : ':warning:';
            const statusText = wasSuccess ? 'Cleaned up' : 'Cleanup completed with warnings';

            const body = `## Preview Deployment

            | Status | Details |
            |--------|---------|
            | ${statusIcon} | ${statusText} |

            **Domain:** ~~\`${{ steps.subdomain.outputs.fqdn }}\`~~ (removed)

            ---
            _Preview environment has been removed. This PR is now closed._`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const botComment = comments.find(c =>
              c.user.login === 'github-actions[bot]' &&
              c.body.includes('## Preview Deployment')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            }

      - name: Save inventory
        if: always()
        run: |
          # Export updated inventory back to secret (for server/site removals)
          cat ~/.deployer/inventory.json | base64 > /tmp/inventory.b64
          echo "Updated inventory saved to /tmp/inventory.b64"
          echo "Update DEPLOYER_INVENTORY secret with this content if resources were deleted."
