# ============================================================================
# PRODUCTION DEPLOY WORKFLOW
# ============================================================================
#
# Deploys to production after specified workflows complete successfully on main.
# This workflow waits for your CI/test workflows to pass before deploying.
#
# ============================================================================
# PREREQUISITES - Complete these steps BEFORE using this workflow
# ============================================================================
#
# This workflow deploys to an existing production server. You must have:
#
# 1. A production server in your inventory (added via server:add or provisioned)
# 2. The production site already created (via site:create)
# 3. Deploy key added to your Git provider
# 4. GitHub secrets configured (see REQUIRED GITHUB SECRETS below)
#
# PRODUCTION SERVER SETUP (One-time):
# -----------------------------------
#
#   # Option A: Add existing server
#   deployer server:add \
#     --name=production \
#     --host=YOUR_SERVER_IP \
#     --username=root \
#     --private-key-path=~/.ssh/id_rsa
#
#   # Install software
#   deployer server:install \
#     --server=production \
#     --php-version=8.3 \
#     --extensions=bcmath,curl,gd,intl,mbstring,mysql,redis,xml,zip \
#     --generate-deploy-key
#
#   # Create production site
#   deployer site:create \
#     --domain=example.com \
#     --server=production \
#     --php-version=8.3 \
#     --www-mode=redirect-to-root \
#     --web-root=public
#
#   # Enable HTTPS
#   deployer site:https --domain=example.com
#
#   # Upload production .env
#   deployer site:shared:push --domain=example.com --local=.env.production --remote=.env
#
# ============================================================================
# WORKFLOW DEPENDENCIES
# ============================================================================
#
# This workflow uses `workflow_run` to wait for other workflows to complete.
# Configure the `workflows` list below with the NAMES of workflows to wait for.
#
# IMPORTANT NOTES:
# - Use workflow NAMES (as shown in GitHub UI), not file names
# - If multiple workflows are listed, this deploys after EACH one completes
# - Recommended: Have ONE CI workflow that runs all checks, then wait for that
# - The deploy only proceeds if the triggering workflow succeeded
#
# EXAMPLE CONFIGURATIONS:
#
#   # Wait for a single CI workflow (recommended)
#   workflows:
#     - "CI"
#
#   # Wait for separate test and lint workflows
#   # (Note: Will trigger deploy twice - once per workflow completion)
#   workflows:
#     - "Tests"
#     - "Lint"
#
# ============================================================================
# REQUIRED GITHUB SECRETS
# ============================================================================
#
#   DEPLOYER_SSH_KEY        - SSH private key for server access
#   DEPLOYER_INVENTORY      - Base64-encoded inventory JSON
#
# ============================================================================

name: Production Deploy

on:
  # ==========================================================================
  # WORKFLOW DEPENDENCIES - Configure which workflows must complete first
  # ==========================================================================
  workflow_run:
    workflows:
      - "CI"              # Change to your CI/test workflow name
      # - "Tests"         # Uncomment to add more workflows
      # - "Lint"
      # - "Build"
    types: [completed]
    branches: [main]

env:
  # ==========================================================================
  # CONFIGURATION - Edit these values for your project
  # ==========================================================================
  PRODUCTION_SERVER: "production"   # Server name from your inventory
  PRODUCTION_DOMAIN: "example.com"  # Your production domain
  PHP_VERSION: "8.3"                # PHP version for deployment
  WEB_ROOT: "public"                # Public directory relative to project root
  KEEP_RELEASES: "5"                # Number of old releases to keep

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Only deploy if the triggering workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # ========================================================================
      # SETUP
      # ========================================================================

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, curl, zip
          coverage: none

      - name: Install DeployerPHP
        run: composer global require deployer-php/deployer-php

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYER_SSH_KEY }}" > ~/.ssh/deployer
          chmod 600 ~/.ssh/deployer
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Restore inventory
        run: |
          mkdir -p ~/.deployer
          echo "${{ secrets.DEPLOYER_INVENTORY }}" | base64 -d > ~/.deployer/inventory.json

      # ========================================================================
      # DEPLOYMENT
      # ========================================================================

      - name: Get server info
        id: server
        run: |
          SERVER_IP=$(deployer server:info --server="${{ env.PRODUCTION_SERVER }}" --json | jq -r '.host')
          echo "ip=${SERVER_IP}" >> $GITHUB_OUTPUT
          echo "Deploying to: ${{ env.PRODUCTION_SERVER }} (${SERVER_IP})"

      - name: Deploy application
        run: |
          deployer site:deploy \
            --domain="${{ env.PRODUCTION_DOMAIN }}" \
            --repo="${{ github.event.repository.ssh_url }}" \
            --branch=main \
            --keep-releases="${{ env.KEEP_RELEASES }}" \
            --yes

      # ========================================================================
      # STATUS NOTIFICATION (Optional)
      # ========================================================================

      - name: Create GitHub deployment status
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            // Create a deployment record
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              environment: 'production',
              auto_merge: false,
              required_contexts: [],
              description: 'Production deployment via DeployerPHP'
            });

            // Mark deployment as successful
            if (deployment.data.id) {
              await github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: deployment.data.id,
                state: 'success',
                environment_url: 'https://${{ env.PRODUCTION_DOMAIN }}',
                description: 'Deployed successfully'
              });
            }

      - name: Post failure notification
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            // Create an issue comment or send notification on failure
            console.log('Production deployment failed!');
            console.log('Workflow: ${{ github.event.workflow_run.name }}');
            console.log('Run ID: ${{ github.run_id }}');

            // Optionally create a GitHub issue for failed deployments
            // await github.rest.issues.create({
            //   owner: context.repo.owner,
            //   repo: context.repo.repo,
            //   title: 'Production deployment failed',
            //   body: `Deployment to production failed.\n\nWorkflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            // });
